use crate::core::settings::{PROFILES_DIR, RUNTIME_CONFIG_FILENAME};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

pub fn get_app_data_dir() -> Result<PathBuf, String> {
    let base = dirs::config_dir()
        .or_else(|| env::current_dir().ok())
        .ok_or_else(|| "Failed to resolve config or current directory".to_string())?;
    let app_dir = base.join("BoxPilot");
    if !app_dir.exists() {
        fs::create_dir_all(&app_dir)
            .map_err(|e| format!("Failed to create app data directory: {}", e))?;
    }
    Ok(app_dir)
}

/// Where a profile's fetched config lives. The profile id is generated by
/// `AppSettings::next_profile_id` ("p1", "p2", …), so it's always a safe
/// file name. The `configs/` directory is created on demand by the writers
/// (`perform_update`, the legacy migration in `AppState::new`).
pub fn profile_config_path(app_dir: &Path, profile_id: &str) -> PathBuf {
    app_dir.join(PROFILES_DIR).join(format!("{}.json", profile_id))
}

/// The prepared config sing-box is launched with (`-c` target). Regenerated
/// from the active profile's canonical `configs/<id>.json` on every start —
/// the canonical files themselves are never written on the start path.
pub fn runtime_config_path(app_dir: &Path) -> PathBuf {
    app_dir.join(RUNTIME_CONFIG_FILENAME)
}

pub fn get_install_dir() -> Result<PathBuf, String> {
    env::current_exe()
        .map_err(|e| format!("Failed to get current executable path: {}", e))?
        .parent()
        .map(|p| p.to_path_buf())
        .ok_or_else(|| "Failed to get executable directory".to_string())
}
