use crate::core::settings::{PROFILES_DIR, RUNTIME_CONFIG_FILENAME};
use crate::i18n::s;
use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// The data dir, created if missing. On Unix it is owner-only (0700), and an
/// existing one is tightened on every call (`restrict_data_dir`): settings
/// hold subscription URLs, which often carry an access token, and profile
/// configs hold server passwords and UUIDs.
pub fn get_app_data_dir() -> Result<PathBuf, String> {
    // Test seam: the import-rollback harness (`src/bin/import_rollback_harness.rs`)
    // points this at a temp dir so integration tests exercise real first-run
    // state without touching user data. Not a supported end-user knob.
    let base = env::var_os("BOXPILOT_DATA_DIR")
        .map(PathBuf::from)
        .or_else(dirs::config_dir)
        .or_else(|| env::current_dir().ok())
        .ok_or_else(|| s().errors.resolve_dir.to_string())?;
    let app_dir = base.join("BoxPilot");
    if !app_dir.exists() {
        // The parent (`~/.config`, or whatever `BOXPILOT_DATA_DIR` names)
        // isn't BoxPilot's: it gets the default mode, only our dir is private.
        fs::create_dir_all(&base)
            .and_then(|()| create_private_dir(&app_dir))
            .map_err(|e| (s().errors.create_app_dir)(&e.to_string()))?;
    }
    restrict_data_dir(&app_dir);
    Ok(app_dir)
}

/// `fs::create_dir_all`, except that on Unix the directories it creates are
/// owner-only (0700). For the data dir and `configs/`. On Windows they
/// inherit the per-user data folder's ACL, which already keeps other users
/// out.
pub fn create_private_dir(path: &Path) -> io::Result<()> {
    let mut builder = fs::DirBuilder::new();
    builder.recursive(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;
        builder.mode(0o700);
    }
    builder.create(path)
}

/// Take group and other access off what older releases left readable in the
/// data dir (created 0755, files 0644): the dir itself and `configs/`, the
/// settings file and its `.bak-` copies, the legacy and runtime configs,
/// every profile config, and leftover temp files. Other files (sing-box's
/// `cache.db`, the Tailscale state dir) are sing-box's and left alone; the
/// 0700 dir covers them. Only BoxPilot's own dirs are touched, never the
/// parent. Unix only; on Windows the per-user data folder's ACL applies.
///
/// sing-box, the privileged TUN copy included (ADR 0003), runs as the same
/// user, so it still reads all of these and works in the dir (`-D`).
///
/// Best effort: a failure goes to stderr and startup goes on.
pub fn restrict_data_dir(app_dir: &Path) {
    #[cfg(unix)]
    {
        restrict_mode(app_dir);
        let configs = app_dir.join(PROFILES_DIR);
        if configs.is_dir() {
            restrict_mode(&configs);
        }
        restrict_files_in(app_dir, holds_secrets);
        restrict_files_in(&configs, |_| true);
    }
    #[cfg(not(unix))]
    let _ = app_dir;
}

/// Data-dir file names `restrict_data_dir` tightens.
#[cfg(unix)]
fn holds_secrets(name: &str) -> bool {
    name.ends_with(".json")
        || name.ends_with(".tmp")
        || name.starts_with(&format!("{}.bak-", crate::core::settings::SETTINGS_FILE))
}

/// Tighten the regular files in `dir` whose name passes `filter`. Symlinks
/// are skipped: their target may be anything.
#[cfg(unix)]
fn restrict_files_in(dir: &Path, filter: impl Fn(&str) -> bool) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let is_file = entry.file_type().is_ok_and(|t| t.is_file());
        if is_file && filter(&entry.file_name().to_string_lossy()) {
            restrict_mode(&entry.path());
        }
    }
}

/// Clear the group and other bits of `path`'s mode, if any are set.
#[cfg(unix)]
fn restrict_mode(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let result = fs::metadata(path).and_then(|meta| {
        let mode = meta.permissions().mode();
        if mode & 0o077 == 0 {
            return Ok(());
        }
        fs::set_permissions(path, fs::Permissions::from_mode(mode & !0o077))
    });
    if let Err(e) = result {
        eprintln!(
            "Failed to restrict permissions on {}: {}",
            path.display(),
            e
        );
    }
}

/// Where a profile's fetched config lives. The profile id is generated by
/// `AppSettings::next_profile_id` ("p1", "p2", …), so it's always a safe
/// file name. The `configs/` directory is created on demand by the writers
/// (`perform_update`, the legacy migration in `AppState::new`), through
/// `create_private_dir`.
pub fn profile_config_path(app_dir: &Path, profile_id: &str) -> PathBuf {
    app_dir.join(PROFILES_DIR).join(format!("{}.json", profile_id))
}

/// The prepared config sing-box is launched with (`-c` target). Regenerated
/// from the active profile's canonical `configs/<id>.json` on every start —
/// the canonical files themselves are never written on the start path.
pub fn runtime_config_path(app_dir: &Path) -> PathBuf {
    app_dir.join(RUNTIME_CONFIG_FILENAME)
}

pub fn get_install_dir() -> Result<PathBuf, String> {
    env::current_exe()
        .map_err(|e| (s().errors.exe_path)(&e.to_string()))?
        .parent()
        .map(|p| p.to_path_buf())
        .ok_or_else(|| s().errors.exe_dir.to_string())
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;
    use crate::core::settings::SETTINGS_FILE;
    use std::os::unix::fs::PermissionsExt;

    fn mode(path: &Path) -> u32 {
        fs::symlink_metadata(path).unwrap().permissions().mode() & 0o777
    }

    fn set_mode(path: &Path, mode: u32) {
        fs::set_permissions(path, fs::Permissions::from_mode(mode)).unwrap();
    }

    #[test]
    fn private_dirs_are_0700() {
        let base = std::env::temp_dir().join(format!("boxpilot-private-{}", std::process::id()));
        let _ = fs::remove_dir_all(&base);
        let configs = base.join("BoxPilot").join(PROFILES_DIR);
        create_private_dir(&configs).unwrap();
        assert_eq!(mode(&base.join("BoxPilot")), 0o700);
        assert_eq!(mode(&configs), 0o700);
        // Existing is fine, as with `create_dir_all`.
        create_private_dir(&configs).unwrap();
        fs::remove_dir_all(&base).unwrap();
    }

    /// What an older release left (0755 dirs, 0644 files) loses group and
    /// other access; sing-box's own files and symlinks are left alone.
    #[test]
    fn restrict_data_dir_tightens_what_older_releases_left() {
        let dir = std::env::temp_dir().join(format!("boxpilot-restrict-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let configs = dir.join(PROFILES_DIR);
        fs::create_dir_all(&configs).unwrap();
        set_mode(&dir, 0o755);
        set_mode(&configs, 0o755);
        let secret_files = [
            dir.join(SETTINGS_FILE),
            dir.join(format!("{}.bak-1700000000", SETTINGS_FILE)),
            dir.join("config.json"),
            dir.join(RUNTIME_CONFIG_FILENAME),
            dir.join("config_check-p1-1-0.tmp"),
            configs.join("p1.json"),
            configs.join(".p2.json.1-0.tmp"),
        ];
        for file in &secret_files {
            fs::write(file, "{}").unwrap();
            set_mode(file, 0o644);
        }
        let cache = dir.join("cache.db");
        fs::write(&cache, "").unwrap();
        set_mode(&cache, 0o644);
        let outside = dir.join("outside.txt");
        fs::write(&outside, "").unwrap();
        set_mode(&outside, 0o644);
        std::os::unix::fs::symlink(&outside, configs.join("link.json")).unwrap();
        // Owner bits stay as they are.
        let read_only = configs.join("p3.json");
        fs::write(&read_only, "{}").unwrap();
        set_mode(&read_only, 0o444);

        restrict_data_dir(&dir);

        assert_eq!(mode(&dir), 0o700);
        assert_eq!(mode(&configs), 0o700);
        for file in &secret_files {
            assert_eq!(mode(file), 0o600, "{}", file.display());
        }
        assert_eq!(mode(&read_only), 0o400);
        assert_eq!(mode(&cache), 0o644);
        assert_eq!(mode(&outside), 0o644);
        // Running again is a no-op.
        restrict_data_dir(&dir);
        assert_eq!(mode(&dir), 0o700);
        set_mode(&read_only, 0o644);
        fs::remove_dir_all(&dir).unwrap();
    }
}
